#!/usr/bin/env bash

set -euo pipefail

script_dir="$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")"
common_sh_path="$(readlink -e "$script_dir/../../bin/common.sh")"
. "$common_sh_path"
unset common_sh_path

PROGRAM_NAME=ext/boost/download

function print_usage ()
{
  cat <<'EOF'
Usage: ext/boost/download [OPTION]...
Download Boost source tree.

  --version=<VERSION>        The version of Boost to download (default: the
                             latest release version).
  --source-dir=<DIR>         The source directory (mandatory).
  -h, --help                 Display this help and exit.
EOF
}

if getopt -T; (( $? != 4 )); then
  die_with_runtime_error "$PROGRAM_NAME" "\`getopt' is not an enhanced version."
fi
opts="$(getopt -n "$PROGRAM_NAME" -l version:,source-dir:,help -- h "$@")"
eval set -- "$opts"

while (( $# > 0 )); do
  arg="$1"
  shift
  case "$arg" in
  --version)
    if (( $# == 0 )); then
      die_with_logic_error "$PROGRAM_NAME"
    fi
    version="$1"
    shift
    ;;
  --source-dir)
    if (( $# == 0 )); then
      die_with_logic_error "$PROGRAM_NAME"
    fi
    source_dir="$1"
    shift
    ;;
  -h|--help)
    set +x
    print_usage
    exit 0
    ;;
  --)
    if (( $# > 0 )); then
      die_with_user_error "$PROGRAM_NAME" "An invalid argument \`$1'."
    fi
    break
    ;;
  *)
    die_with_user_error "$PROGRAM_NAME" "An invalid argument \`$arg'."
    ;;
  esac
done

if [[ ! -v version ]]; then
  version="$(curl -fLsS 'https://www.boost.org/users/history/'                          \
               | grep -Eo 'Version[[:space:]]+[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+' \
               | grep -Eo '[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+'                    \
               | LANG=C.UTF-8 sort -Vu                                                  \
               | tail -n 1)" \
    || die_with_runtime_error "$PROGRAM_NAME" "Failed to guess Boost latest release version."
  if [[ ! $version =~ ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$ ]]; then
    die_with_runtime_error "$PROGRAM_NAME" "Failed to eguess Boost latest release version."
  fi
fi
if [[ ! $version =~ ^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$ ]]; then
  die_with_user_error "$PROGRAM_NAME" "An invalid value \`$version' for \`--version' option."
fi

temp_dir="$(mktemp -d)" \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to create a temporary directory."
push_rollback_command "rm -rf \"$temp_dir\""

if [[ ! -v source_dir ]]; then
  die_with_user_error "$PROGRAM_NAME" "\`--source-dir' option is mandatory."
fi
if [[ $(readlink -m "$source_dir") != $(cd "$temp_dir" >/dev/null && readlink -m "$source_dir") ]]; then
  die_with_user_error "$PROGRAM_NAME" "A relative path \`$source_dir' is specified for \`--source-dir' option, but is expected to be an absolute one."
fi

if [[ -e $source_dir ]]; then
  rm -rf "$source_dir"
fi
mkdir -p "$source_dir" \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to create the source directory \`$source_dir'."

# 379CE192D401AB61: rsa4096 2015-02-17 Bintray (by JFrog) <bintray@bintray.com>
key_ids=(379CE192D401AB61)
key_servers=('hkp://keys.gnupg.net:80'               \
             'hkp://zimmermann.mayfirst.org:80'      \
             'hkp://pgp.key-server.io:80'            \
             'hkp://keyserver.ubuntu.com:80'         \
             'hkp://p80.pool.sks-keyservers.net:80')
for key_server in "${key_servers[@]}"; do
  timeout 30 gpg --homedir "$temp_dir/.gnupg" --batch --keyserver "$key_server" --recv-keys "${key_ids[@]}" && break
done

url_prefix="https://dl.bintray.com/boostorg/release/$version/source"
tarball_name="boost_$(tr . _ <<<"$version").tar.bz2"

(cd "$temp_dir" && curl -fLsSo "$tarball_name" "$url_prefix/$tarball_name") \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to download \`$tarball_name'."
(cd "$temp_dir" && curl -fLsSo "$tarball_name.asc" "$url_prefix/$tarball_name.asc") \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to download \`$tarball_name.asc'."
gpg --homedir "$temp_dir/.gnupg" --batch --verify "$temp_dir/$tarball_name.asc" "$temp_dir/$tarball_name" \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to verify the signature in \`$tarball_name.asc'."

tar xf "$temp_dir/$tarball_name" -C "$source_dir" --strip-components=1 \
  || die_with_runtime_error "$PROGRAM_NAME" "Failed to expand \`$tarball_name'."
